name: Veracode Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Veracode Auto Package
  veracode-package:
    runs-on: ubuntu-latest
    container:
      image: node:18.10.0-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Veracode Auto Package
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source ./ --trust --output ./verascan/

      - name: Upload Verascan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: verascan
          path: ./verascan/

  # Job 2: Veracode SCA Scan (runs in parallel with the packaging job)
  sca-scan:
    runs-on: ubuntu-latest
    container:
      image: node:18.10.0-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Veracode SCA Scan
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan . --update-advisor --skip-vms
        env:
          SRCCLR_API_TOKEN: ${{ secrets.VERACODE_AGENT_TOKEN }}

  # Job 3: Veracode Upload and Scan (depends on the packaging job)
  upload-and-scan:
    runs-on: ubuntu-latest
    needs: veracode-package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Verascan Artifact
        uses: actions/download-artifact@v3
        with:
          name: verascan
          path: ./verascan/

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: ${{ github.repository }}
          createprofile: true
          filepath: './verascan/'  # This should match the directory where the artifact is downloaded
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          deleteincompletescan: 2
          criticality: "High"

